## Introduction

Week 4:
1. Choose a corpus of interest.
2. How many total unique words are in the corpus? (Please feel free to define unique words in any interesting,
defensible way).
3. Taking the most common words, how many unique words represent half of the total words in the corpus?
4. Identify the 200 highest frequency words in this corpus.
5. Create a graph that shows the relative frequency of these 200 words.
6. Does the observed relative frequency of these words follow Zipf’s law? Explain.
7. In what ways do you think the frequency of the words in this corpus differ from “all words in all corpora.”

## Setup

In [21]:
import pandas as pd #uncomment to run pandas
import nltk, re, pprint
from nltk import word_tokenize
from nltk.corpus import reuters
from nltk.corpus import stopwords
from nltk.probability import FreqDist
from IPython.display import display

In [22]:
nltk.download('punkt')
nltk.download('stopwords')
rcorp=nltk.download('reuters')

[nltk_data] Downloading package punkt to C:\Users\Dom
[nltk_data]     Cobb\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to C:\Users\Dom
[nltk_data]     Cobb\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package reuters to C:\Users\Dom
[nltk_data]     Cobb\AppData\Roaming\nltk_data...
[nltk_data]   Package reuters is already up-to-date!

## Summary Statistics

In [23]:
rcategories = reuters.categories()

In [24]:
#uncomment to print complete list of words--------------
#total = len(reuters.paras())
#runtotal = 0
#print(("%-15s || %s") % ("Category", "Number of documents out of %d total") % (total))
#for c in rcategories:
#    doccount = len(reuters.paras(categories=[c]))
#    runtotal += doccount
#    print(("%-15s || %d") % (c, doccount))

In [25]:
print("Average categories per article: %.2f" % ((runtotal * 1.0) / total))
print("Average articles per category: %.2f" % ((total * 1.0) / len(rcategories)))

Average categories per article: 1.23
Average articles per category: 132.08

## Total Unique Words

In [26]:
#Using FreqDist function
freqwords = FreqDist(reuters.words())
len(freqwords)

41600

In [27]:
#Using Set function
r1=nltk.corpus.reuters.words()
r1unique = set(r1)
len(r1unique)

41600

In [28]:
# Remove non-alpha characters
r1 = [w for w in r1 if w.isalpha()]

In [29]:
# Remove 'stop words'
r1 = [w for w in r1 if w not in stopwords.words('english')] #issues processing stopword removal?

In [30]:
# Collect highest frequency words
freqr1 = nltk.FreqDist(r1)

# Show highest frequency words

pd.set_option('display.max_rows', len(freqr1.most_common(200)))
print (display(pd.DataFrame(freqr1.most_common(200), columns = ['word','frequency'])))

              word  frequency
0             said      25224
1              mln      18037
2               vs      14120
3             dlrs      11730
4              The      10968
5              pct       9093
6               lt       8694
7              cts       7953
8                U       6388
9                S       6382
10            year       6310
11         billion       5652
12           would       4634
13            loss       4528
14         company       4399
15             Net       3381
16             Shr       3202
17            last       3004
18           share       2953
19          profit       2821
20             Inc       2771
21             one       2584
22          shares       2525
23             oil       2518
24          market       2497
25            also       2483
26             two       2441
27            Corp       2405
28          tonnes       2375
29           stock       2346
30            Revs       2283
31           trade       2271
32              TO       2257
33              It       2060
34             QTR       2053
35             net       2046
36             per       2027
37           April       1978
38          prices       1951
39           March       1864
40         quarter       1766
41            Bank       1718
42             new       1698
43           price       1663
44        February       1630
45            rate       1624
46              He       1614
47         January       1613
48               A       1611
49           Japan       1594
50      government       1567
51             NET       1558
52            week       1538
53           offer       1537
54           three       1505
55              In       1479
56            bank       1472
57          dollar       1462
58              Co       1462
59           could       1431
60            told       1424
61           first       1363
62       agreement       1336
63        expected       1327
64           today       1320
65             INC       1315
66             tax       1311
67              IN       1296
68      production       1283
69           month       1266
70           sales       1262
71        interest       1253
72            rose       1249
73           rates       1211
74             Ltd       1209
75         foreign       1209
76            five       1203
77             dlr       1184
78             But       1157
79            rise       1145
80           group       1140
81        increase       1136
82           added       1112
83             end       1110
84             stg       1102
85            NOTE       1099
86           total       1088
87         current       1086
88         meeting       1065
89             Avg       1062
90            shrs       1056
91            Oper       1048
92          common       1042
93             May       1033
94        exchange       1032
95          growth       1019
96        official       1009
97              EC        999
98         exports        994
99          months        993
100           made        983
101           CORP        958
102            six        956
103      spokesman        952
104        earlier        941
105       earnings        936
106          major        935
107       December        928
108           four        922
109       Japanese        916
110           cash        915
111      countries        911
112           sale        910
113         agreed        902
114     operations        894
115          board        882
116          Sales        873
117           West        873
118          banks        869
119            may        865
120         export        862
121           fell        855
122        sources        850
123       compared        847
124         report        843
125            due        842
126           mths        840
127          years        839
128      officials        836
129         United        836
130         around        835
131            yen        834
132       industry        833
133       includes        826
134  International        822
135      companies        819
136       American        817
137            New        797
138          world        794
139     investment        793
140       business        792
141   shareholders        787
142           time        786
143       economic        784
144      statement        784
145            cut        781
146        imports        776
147            shr        772
148          wheat        766
149           debt        764
150           next        763
151       reported        761
152              K        756
153             OF        750
154            FOR        749
155        markets        748
156        deficit        747
157           gain        741
158          since        741
159         record        741
160            buy        734
161          money        733
162              I        732
163          lower        729
164           nine        727
165         period        726
166           June        726
167           SAYS        725
168            PCT        717
169       analysts        708
170           take        708
171          ended        706
172         higher        704
173       products        703
174       dividend        698
175          based        693
176             We        690
177          prior        686
178      announced        683
179              O        683
180       currency        676
181           Year        672
182       reserves        670
183        figures        667
184        trading        666
185    acquisition        658
186          Group        654
187         policy        653
188          stake        645
189         States        643
190           term        640
191            ago        639
192        surplus        638
193      financial        637
194         demand        636
195           high        636
196       European        633
197            day        632
198         merger        632
199           unit        629

None

In [31]:
# Show word counts and relative frequencies
r1mostfreq = pd.DataFrame(freqr1.most_common(200),columns=['word','count']) ## uncomment to run pandas
r1mostfreq['PctAppearing'] = r1mostfreq['count']/float(len(r1)) ## uncomment to run pandas
r1mostfreq.head(20) ## uncomment to run pandas

       word  count  PctAppearing
0      said  25224      0.027565
1       mln  18037      0.019711
2        vs  14120      0.015430
3      dlrs  11730      0.012819
4       The  10968      0.011986
5       pct   9093      0.009937
6        lt   8694      0.009501
7       cts   7953      0.008691
8         U   6388      0.006981
9         S   6382      0.006974
10     year   6310      0.006896
11  billion   5652      0.006177
12    would   4634      0.005064
13     loss   4528      0.004948
14  company   4399      0.004807
15      Net   3381      0.003695
16      Shr   3202      0.003499
17     last   3004      0.003283
18    share   2953      0.003227
19   profit   2821      0.003083

In [32]:
#freqr1

In [33]:
str(freqr1)

'<FreqDist with 39541 samples and 915079 outcomes>'